stages:
  - publish_build_to_pre_qa

publish_build_to_pre_qa:
  stage: publish_build_to_pre_qa
  image: python:3.8-alpine
  artifacts:
    when: on_success
    paths:
      - artifacts/*
  before_script:
    - apk add --update --no-cache make curl bash git
    - curl -L https://github.com/screwdriver-cd/gitversion/releases/download/v1.1.1/gitversion_linux_amd64 -o /usr/local/bin/gitversion && chmod +x /usr/local/bin/gitversion
    - eval $(ssh-agent -s)
  script:
    - mkdir -p artifacts
    - pip install requests
    - VERSION=$(git tag --sort=-creatordate | head -n 1)
    - echo "Build version - $VERSION"
    # Upload ESS-ContentUpdate build to Pre-QA
    - python security_content_automation/publish_build_to_pre_qa/publish_build_to_pre_qa.py --version $VERSION --builds DA-ESS-ContentUpdate
    # Upload SSA-Content build to Pre-QA
    - python security_content_automation/publish_build_to_pre_qa/publish_build_to_pre_qa.py --version $VERSION --builds SSA_Content
  after_script:
    - cp publish_build_to_pre_qa.log artifacts/publish_build_to_pre_qa.log
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always
