stages:
  - Demo

demo:
  stage: Demo
  image: python:3.8-alpine
  script:
    - echo "Hello Aliens!"  
  rules:
    - if: '$CI_COMMIT_REF_NAME =~ /^v[0-9]+\.[0-9]+\.[0-9]$/'
      when: always
      
      
      
